### ISSUE TITLE
Can't run example project

### ISSUE THREAD

**Issue by rbuchmann** [HCADatalab/powderkeg#3]
I get the following when requiring powderkeg, using version 0.4.0 (in cider/nrepl):

```
(require '[powderkeg.core :as keg])
Preparing for self instrumentation.
Ouroboros succesfully eating its own tail!
Counting classes.
Retrieving bytecode of 7851 classes dynamically defined by Clojure (out of 16272 classes)... done!
Instrumenting clojure.lang.Var... done!
CompilerException java.lang.ClassNotFoundException: org.apache.spark.SparkEnv, compiling:(powderkeg/kryo.clj:41:7) 
```

My project.clj requires clojure 1.7 and is otherwise empty.

**Comment by cgrand** [comment]
Add spark 1.5.2 as a dependency to your project.

Le lun. 5 déc. 2016 à 18:40, Rasmus Buchmann <notifications@github.com> a
écrit :

**Comment by cgrand** [comment]
[org.apache.spark/spark-core_2.10 "1.5.2"]
                                  [org.apache.spark/spark-streaming_2.10
"1.5.2"]

Le lun. 5 déc. 2016 à 18:46, Christophe Grand <christophe@cgrand.net> a
écrit :

**Comment by rbuchmann** [comment]
Great, that fixed it! Thanks for the immediate response 👍

**Comment by cgrand** [comment]
Documented deps in `README.md` https://github.com/HCADatalab/powderkeg/commit/bce7ba3ff8ab682e344ae6263e131566b2fc726a

**Comment by plandes** [comment]
FYI--This works in 0.5.1 with Spark 2.1.0
