### ISSUE TITLE
How to call a side-effect function for each element of a rdd (foreach)

### ISSUE THREAD

**Issue by dpom** [HCADatalab/powderkeg#43]
I defined an rdd with:
(def occs (-> orders
              (keg/rdd
               (map read-string)
               (map #(comb/combinations % 2))
               (mapcat identity)
               (map sort))
              (keg/by-key :key identity
                          :pre x/count
                          :post (x/reduce +))))

How I call a side-effect function (write to a db)  for each element of the occs (an equivalent of spark's foreach)?

**Comment by cgrand** [comment]
See `do-rdd`. The binding vector is for resources management (e.g. db connection).

**Comment by dpom** [comment]
Thanks, that's exactly what I needed.
