### ISSUE TITLE
Better document and tool for spark-submit

### ISSUE THREAD

**Issue by ghost** [HCADatalab/powderkeg#6]
This occurs when running the example, after connecting to the cluster.

repl output: https://gist.github.com/brianmingus/cdba100687cd14b17f59a70763cbb2fd
stack trace: https://gist.github.com/brianmingus/081d4d8b4d5017e0327da9c226f5e8de

**Comment by brianmingus** [comment]
`Retrieving bytecode of 8027 classes dynamically defined by Clojure (out of 15666 classes)... done!                                                                                               
Instrumenting clojure.lang.Var... done!                                                                                                                                                          
Using Powderkeg's default logging profile: powderkeg/log4j_default.properties                                                                                                                    
ConcurrentModificationException   java.util.Vector$Itr.checkForComodification (Vector.java:1184)                                                                                                 
CompilerException com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException                                                                                             
Serialization trace:                                                                                                                                                                             
classes (sun.misc.Launcher$AppClassLoader)                                                                                                                                                       
classloader (java.security.ProtectionDomain)                                                                                                                                                     
context (java.security.AccessControlContext)                                                                                                                                                     
acc (clojure.lang.DynamicClassLoader)                                                                                                                                                            
classLoader (akka.actor.ReflectiveDynamicAccess)                                                                                                                                                 
_pm (akka.actor.ActorSystemImpl)                                                                                                                                                                 
actorSystem (org.apache.spark.SparkEnv)                                                                                                                                                          
env (org.apache.spark.api.java.JavaSparkContext)                                                                                                                                                 
vars (powderkeg.core$barrier_BANG_$fn__20668$fn__20669)                                                                                                                                          
fn (clojure.lang.Delay), compiling:(/home/ubuntu/thinktopic/code/style-data/src/style_data/core.clj:7:1)     `

**Comment by ghost** [comment]
This is because, as the documentation notes, when running in an application you have to set `keg/*sc*` with a SparkContext. However, the documentation should give an example that actually works.

```clj
(ns some.ns
  (:require [powderkeg.core :as keg]))

(binding [keg/*sc* (keg/connect! "local[*]")]
  (into [] ; no collect, plain Clojure
    (keg/rdd ["This is a firest line"  ; here we provide data from a clojure collection.
              "Testing spark"
              "and powderkeg"
              "Happy hacking!"]
     (filter #(.contains % "spark")))))
```

**Comment by cgrand** [comment]
Which command line did you use?

**Comment by ghost** [comment]
This is when using CIDER in emacs. The instructions are correct, but they
would be better od you pasted in my example code here.

**Comment by cgrand** [comment]
I don't see the meaningful difference between the current example (raw require out of ns) and your example (require inside ns form). Not a CIDER user could you elaborate? Thanks.

Btw since I misunderstood your problem I made these changes https://github.com/HCADatalab/powderkeg/commit/6abf666a3f8bc5486e953b3bde11b01d82a7b459

**Comment by cgrand** [comment]
Maybe I misunderstood the context: you spark-submitted a repl and then tried to run the example. In the end all you have needed to do was:
```clj
(ns some.ns
(:require [powderkeg.core :as keg]))

;;;;;;;;;;;;;;
;; no keg/connect! because spark-submit
;;;;;;;;;;;;;;

(into [] ; no collect, plain Clojure
(keg/rdd ["This is a firest line" ; here we provide data from a clojure collection.
"Testing spark"
"and powderkeg"
"Happy hacking!"]
(filter #(.contains % "spark"))))```

Am I correct?

**Comment by ghost** [comment]
Apologies, I fixed the code above. If you could just paste that into the docs.

(Regarding your recent addition: that is incorrect. You have to use `binding`.)

**Comment by ghost** [comment]
It occurs to me that using `binding` breaks repl-driven development. Instead:

```clj
(alter-var-root #'keg/*sc* (fn [_] (keg/connect! "local[*]"))) ; seems like this should be wrapped up in a fn

(into [] ; no collect, plain Clojure
    (keg/rdd ["This is a firest line"  ; here we provide data from a clojure collection.
              "Testing spark"
              "and powderkeg"
              "Happy hacking!"]
     (filter #(.contains % "spark"))))
```

**Comment by cgrand** [comment]
`(keg/connect! "local[*]")` already *does* the `alter-var-root`.

So following the example from the `README.md` should have worked (modulo substituting `"spark://macbook-pro.home:7077"` by `"local[*]"`). Why/how didn't it worked for you?

Dynamic binding of `*sc*` is on hold at the moment, there are few use cases for multiple spark connections at a time (and spark tries to dissuade you). Hence the document and code changes I made while misunderstanding your issue.

**Comment by ghost** [comment]
Indeed, it is working. Not sure what happened before.
